import { computed } from 'vue';
import type { Ref } from 'vue';
import type { UrlParamSpecs } from './useUrlState';
import { decodeInt, decodeKey, encodeCoord, decodeCoord } from '@/utils/urlCodec';
import { parseSeed } from '@/utils/rng';
import type { Coord, NodeId } from '@/types';
import { algorithms as sortAlgorithms } from '@/algorithms';
import type { SortAlgoKey } from '@/algorithms';
import { algorithms as searchAlgorithms } from '@/algorithms/search';
import type { SearchAlgoKey } from '@/algorithms/search';
import { algorithms as pathAlgorithms } from '@/algorithms/pathfinding';
import type { PathAlgoKey } from '@/algorithms/pathfinding';
import { algorithms as graphAlgorithms } from '@/algorithms/graph';
import type { GraphAlgoKey } from '@/algorithms/graph';

/**
 * urlParams — pure `UrlParamSpecs` factories, one per category.
 *
 * Deliberately plain functions rather than composables that call
 * `useUrlState` themselves: keeping the encode/decode pairs free of
 * `useRouter()` is what lets `urlParams.test.ts` exercise every codec with
 * bare `ref(...)`s, no router and no mounted component required.
 */

// ---- shared helpers ---------------------------------------------------------

/** Encodes a seed, which is always written — it's the whole point of a shareable link. */
function encodeSeed(seed: number): string {
  return String(seed);
}

/** Rejects malformed input via `parseSeed`, converting its `null` into `undefined`
 *  ("reject, keep current value") to match `UrlParamSpec.decode`'s contract. */
function decodeSeed(raw: string): number | undefined {
  const parsed = parseSeed(raw);
  return parsed === null ? undefined : parsed;
}

// ---- sorter ------------------------------------------------------------------

export const SORTER_DEFAULTS = {
  algo: 'bubble' as SortAlgoKey,
  size: 45,
  speed: 60,
};

export function sorterUrlParams(refs: {
  algoKey: Ref<SortAlgoKey>;
  size: Ref<number>;
  speed: Ref<number>;
  seed: Ref<number>;
}): UrlParamSpecs<{ algo: SortAlgoKey; size: number; speed: number; seed: number }> {
  return {
    algo: {
      ref: refs.algoKey,
      encode: (k) => (k === SORTER_DEFAULTS.algo ? null : k),
      decode: (raw) => decodeKey(sortAlgorithms, raw),
    },
    size: {
      ref: refs.size,
      encode: (n) => (n === SORTER_DEFAULTS.size ? null : String(n)),
      decode: (raw) => decodeInt(raw, 10, 100),
      debounceMs: 250,
    },
    speed: {
      ref: refs.speed,
      encode: (n) => (n === SORTER_DEFAULTS.speed ? null : String(n)),
      decode: (raw) => decodeInt(raw, 1, 100),
      debounceMs: 250,
    },
    seed: {
      ref: refs.seed,
      encode: encodeSeed,
      decode: decodeSeed,
    },
  };
}

// ---- searcher ------------------------------------------------------------------

export const SEARCHER_DEFAULTS = {
  algo: 'binary' as SearchAlgoKey,
  size: 20,
  speed: 60,
  // Mirrors the composable's initial `ref(0)`; `generate()` immediately
  // overwrites it with a seed-derived value, so in practice `target` behaves
  // like `seed` and is almost always written.
  target: 0,
};

export function searcherUrlParams(refs: {
  algoKey: Ref<SearchAlgoKey>;
  size: Ref<number>;
  speed: Ref<number>;
  seed: Ref<number>;
  target: Ref<number>;
}): UrlParamSpecs<{
  algo: SearchAlgoKey;
  size: number;
  speed: number;
  seed: number;
  target: number;
}> {
  return {
    algo: {
      ref: refs.algoKey,
      encode: (k) => (k === SEARCHER_DEFAULTS.algo ? null : k),
      decode: (raw) => decodeKey(searchAlgorithms, raw),
    },
    size: {
      ref: refs.size,
      encode: (n) => (n === SEARCHER_DEFAULTS.size ? null : String(n)),
      decode: (raw) => decodeInt(raw, 10, 50),
      debounceMs: 250,
    },
    speed: {
      ref: refs.speed,
      encode: (n) => (n === SEARCHER_DEFAULTS.speed ? null : String(n)),
      decode: (raw) => decodeInt(raw, 1, 100),
      debounceMs: 250,
    },
    seed: {
      ref: refs.seed,
      encode: encodeSeed,
      decode: decodeSeed,
    },
    target: {
      ref: refs.target,
      encode: (n) => (n === SEARCHER_DEFAULTS.target ? null : String(n)),
      // Bounded to the dataset's own value range (1..99, generated by
      // `randomSortedArray`), plus 0 as the untouched sentinel default.
      decode: (raw) => decodeInt(raw, 0, 99),
    },
  };
}

// ---- pathfinder ------------------------------------------------------------------

export function pathfinderUrlParams(
  refs: {
    algoKey: Ref<PathAlgoKey>;
    speed: Ref<number>;
    seed: Ref<number>;
    start: Ref<Coord>;
    end: Ref<Coord>;
  },
  dims: { rows: number; cols: number },
): UrlParamSpecs<{
  algo: PathAlgoKey;
  speed: number;
  seed: number;
  start: Coord;
  end: Coord;
}> {
  const defaultAlgo: PathAlgoKey = 'bfs';
  const defaultSpeed = 60;
  const defaultStart: Coord = { row: Math.floor(dims.rows / 2), col: 0 };
  const defaultEnd: Coord = { row: Math.floor(dims.rows / 2), col: dims.cols - 1 };
  const sameCoord = (a: Coord, b: Coord) => a.row === b.row && a.col === b.col;

  return {
    algo: {
      ref: refs.algoKey,
      encode: (k) => (k === defaultAlgo ? null : k),
      decode: (raw) => decodeKey(pathAlgorithms, raw),
    },
    speed: {
      ref: refs.speed,
      encode: (n) => (n === defaultSpeed ? null : String(n)),
      decode: (raw) => decodeInt(raw, 1, 100),
      debounceMs: 250,
    },
    seed: {
      ref: refs.seed,
      encode: encodeSeed,
      decode: decodeSeed,
    },
    start: {
      ref: refs.start,
      encode: (c) => (sameCoord(c, defaultStart) ? null : encodeCoord(c)),
      // Out-of-bounds is REJECTED rather than clamped: a clamped coordinate
      // silently lands on a different cell, which is worse than falling back
      // to the composable's current start.
      decode: (raw) => decodeCoord(raw, dims.rows, dims.cols),
    },
    end: {
      ref: refs.end,
      encode: (c) => (sameCoord(c, defaultEnd) ? null : encodeCoord(c)),
      decode: (raw) => decodeCoord(raw, dims.rows, dims.cols),
    },
  };
}

/** Adapts a `reactive<Coord>` field pair into the `Ref<Coord>` shape `UrlParamSpec`
 *  needs — `useUrlState` reads/writes `.value`, which a `reactive()` object doesn't
 *  have. A `WritableComputedRef<Coord>` satisfies `Ref<Coord>` and keeps the
 *  composable's existing reactive `start`/`end` as the single source of truth. */
export function coordRef(target: Coord): Ref<Coord> {
  return computed({
    get: () => ({ row: target.row, col: target.col }),
    set: (value) => {
      target.row = value.row;
      target.col = value.col;
    },
  });
}

// ---- graph traversal ------------------------------------------------------------------

export const GRAPH_DEFAULTS = {
  algo: 'bfs' as GraphAlgoKey,
  speed: 60,
};

export function graphUrlParams(refs: {
  algoKey: Ref<GraphAlgoKey>;
  speed: Ref<number>;
  seed: Ref<number>;
  startId: Ref<NodeId | null>;
}): UrlParamSpecs<{
  algo: GraphAlgoKey;
  speed: number;
  seed: number;
  start: NodeId | null;
}> {
  return {
    algo: {
      ref: refs.algoKey,
      encode: (k) => (k === GRAPH_DEFAULTS.algo ? null : k),
      decode: (raw) => decodeKey(graphAlgorithms, raw),
    },
    speed: {
      ref: refs.speed,
      encode: (n) => (n === GRAPH_DEFAULTS.speed ? null : String(n)),
      decode: (raw) => decodeInt(raw, 1, 100),
      debounceMs: 250,
    },
    seed: {
      ref: refs.seed,
      encode: encodeSeed,
      decode: decodeSeed,
    },
    start: {
      ref: refs.startId,
      // `null` (no node picked yet) is the only omitted case — every real
      // node id, including node 0, is written so a shared link reproduces
      // the exact traversal start.
      encode: (id) => (id === null ? null : String(id)),
      // Node ids are non-negative integers assigned by `generateGraph`
      // (`0..nodeCount - 1`); the upper bound here is a generous sanity cap,
      // not tied to any particular graph's actual size.
      decode: (raw) => decodeInt(raw, 0, 9999),
    },
  };
}
